# Generated by Django 5.1.4 on 2025-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikCMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devblog',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devblog',
            name='blurb',
            field=models.TextField(null=True),
        ),
    ]
