# Generated by Django 5.1.4 on 2024-12-10 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduserdata',
            name='followed_users',
            field=models.ManyToManyField(related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendeduserdata',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
