# Generated by Django 5.1.4 on 2024-12-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extendeduserdata_followed_users_and_more'),
        ('feed', '0005_genre_tag_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduserdata',
            name='bookmarked_posts',
            field=models.ManyToManyField(related_name='bookmarked_posts', to='feed.genericpost'),
        ),
        migrations.AddField(
            model_name='extendeduserdata',
            name='followed_games',
            field=models.ManyToManyField(related_name='followed_games', to='feed.game'),
        ),
    ]
