# Generated by Django 5.1.4 on 2024-12-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extendeduserdata_bookmarked_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserdata',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
