# Generated by Django 5.1.4 on 2024-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_extendeduserdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduserdata',
            name='profile_pic',
            field=models.ImageField(default='placeholder/avatar_placeholder.png', null=True, upload_to='avatars/'),
        ),
    ]
