# Generated by Django 5.1.4 on 2024-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
