# Generated by Django 5.1.4 on 2024-12-09 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_userpost_date_posted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpostlikes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpostlikes',
            name='user',
        ),
        migrations.CreateModel(
            name='GenericPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('post_content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(default=None, null=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('immediate_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_post', to='feed.genericpost')),
                ('likes', models.ManyToManyField(default=None, null=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('top_level_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.genericpost')),
                ('keywords', models.ManyToManyField(default=None, null=True, to='feed.keyword')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.DeleteModel(
            name='UserPostLikes',
        ),
    ]
