# Generated by Django 5.1.4 on 2024-12-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_rename_keyword_tag_tag_game_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpost',
            name='related_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.game'),
        ),
    ]
