# Generated by Django 5.1.4 on 2024-12-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_genericpost_related_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.TextField()),
                ('content', models.TextField()),
                ('related_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.game')),
            ],
        ),
    ]
