# Generated by Django 5.1.4 on 2025-01-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_devblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevBlog',
        ),
    ]
