# Generated by Django 5.1.4 on 2024-12-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_delete_devblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpost',
            name='related_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_per_game', to='feed.game'),
        ),
    ]
